### PR TITLE
[wip] Numeric, text and datetime types

### PR DESCRIPTION
**Pull request by vweevers**
Numeric types as per #1 :
- [x] smallint
- [x] integer
- [x] bigint
- [x] decimal
- [x] numeric
- [x] real
- [x] double precision
- [x] serial
- [x] bigserial

Text as per #2:
- [x] char, varchar
- [x] bpchar alias
- [x] text

Datetime as per #3:
- [ ] timestamp (see comments below)
- [ ] date
- [ ] time
- [ ] interval

Other tasks:
- [x] shortcuts in the form of `validate[platform]`
- [x] PR for `pg-metadata`: see ironSource/node-pg-metadata#2
- [ ] Check storage limit of float4/8 on Redshift, if it matches PostgreSQL

### CODE REVIEW

**Comment by vweevers** [comment]
@kessler: Postgres and Redshift have different maximum precisions and scales for numeric/decimal types. Whose rules should pg-validate follow?

**Comment by vweevers** [comment]
Also, in Redshift, `float` is an alias for `double precision`, nothing more. But in postgres: 

> PostgreSQL accepts float(1) to float(24) as selecting the real type, while float(25) to float(53) select double precision.

**Comment by vweevers** [comment]
There are similar questions for the text and date types, so I'm gonna hold off on implementing those.

**Comment by vweevers** [comment]
The platform (or should it be "vendor"?) can now be specified like so:

``` js
var errors = validate.object({
    foo: 1280000,
    bar: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
}, metadata, { platform: validate.REDSHIFT })
```

And defaults to postgres.

**Comment by kessler** [comment]
Wouldn't it be cooler if it was something like:

validate.object() // default or possibly autodetect somehow
validate.redshift.object()
validate.pg.object()

?

**Comment by vweevers** [comment]
I usually prefer options for this kind of thing, because it's easier for consumers to build on top of it (passing options along a chain). Could also do both, so that `validate.redshift` is a shortcut to `{ platform: redshift }`.

**Comment by vweevers** [comment]
Another option is to make a separate `pg-validate-redshift` module, and have it override types and options where necessary.

**Comment by kessler** [comment]
I'll go for your hybrid solution, interface + options separate module seems
like using a crane to lift a small box

**Comment by vweevers** [comment]
OK. I like that metaphor.

**Comment by vweevers** [comment]
The trouble of merging wouldn't be worth it, so this is now a PR for all the types.

I've described some of the current limitations for datetime types in the [readme](https://github.com/vweevers/node-pg-validate/tree/num-types#datetime). @kessler : could you read those and tell me what to prioritize?

**Comment by vweevers** [comment]
Did an experiment today: generated an `interval` validator from PostgreSQL C source code, with emscripten. Takes some milliseconds to load (subsequent calls are very fast), but every interval format supported by postgres can be validated.

**Comment by vweevers** [comment]
@kessler: one thing I forgot to mention: in some of the tests, an actual postgres database is used to verify validation results. For example, for the range of integer types, a `SELECT $1::integer AS res` query is executed, once with a valid value for $1, once with the maximum value + 1. The test asserts that when postgres returns an error for the query, our `type.isValidValue(..)` returns `false` too. Similar tests are done for numeric types and dates.

And it might be a good idea to run these tests against a Redshift database too, to ensure storage limits etc match. If you can provide credentials, I'll quickly run the tests against redshift and if necessary change the parameters of the validators.

**Comment by kessler** [comment]
@vweevers I can do that, but I'm not sure that basing tests on actual databases is a good idea... can't you use a mock?

**Comment by vweevers** [comment]
No, these tests verify that computed constants match actual database limits. You can't do that with a mock (what would be the point of comparing one js constant with another). These tests were quite useful to me during implementation - was basically to ensure that my interpretation of the postgres documentation was correct.

Without a database connection BTW, these kinds of tests are skipped. So a database is not required to run the test suite, and because of that, I don't see a downside.

**Comment by kessler** [comment]
Well a redshift cluster is a costly thing to run. I can let you work on the production cluster but you need to be careful. I'll pass credentials through secure communications

**Pull request merged**
